-- =========================================================
-- HoneyTrace Supabase database
-- Run this entire script in Supabase SQL Editor.
-- =========================================================

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('buyer', 'seller')),
  created_at timestamptz not null default now()
);

create table if not exists public.honey_batches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  batch_id text not null unique,
  honey_type text not null,
  quantity text not null,
  harvest_date date not null,
  origin text not null,
  status text not null default 'Verified',
  blockchain_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists honey_batches_user_id_idx
  on public.honey_batches(user_id);

create index if not exists honey_batches_batch_id_idx
  on public.honey_batches(batch_id);

-- Create a profile automatically whenever a new Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (user_id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', 'HoneyTrace User'),
    coalesce(new.raw_user_meta_data ->> 'role', 'buyer')
  )
  on conflict (user_id) do update
    set full_name = excluded.full_name,
        role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.honey_batches enable row level security;

-- Remove old policies if you re-run this script.
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Authenticated users can view public seller profile fields" on public.profiles;

drop policy if exists "Users can insert own honey batches" on public.honey_batches;
drop policy if exists "Users can view own honey batches" on public.honey_batches;
drop policy if exists "Anyone can verify honey batch by QR" on public.honey_batches;

-- Profiles: a logged-in user can read/update their own profile.
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Honey batches: only the seller who owns a batch can insert/read it
-- through the authenticated dashboard.
create policy "Users can insert own honey batches"
on public.honey_batches
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can view own honey batches"
on public.honey_batches
for select
to authenticated
using ((select auth.uid()) = user_id);

-- QR verification must work for a consumer who is not logged in.
-- This exposes only honey_batches rows intended for public verification.
-- For a production system, use a dedicated public verification view/API
-- if you need to hide additional internal fields.
create policy "Anyone can verify honey batch by QR"
on public.honey_batches
for select
to anon
using (true);

-- Least-privilege grants for the browser client.
revoke all on table public.profiles from anon;
grant select, update on table public.profiles to authenticated;

revoke all on table public.honey_batches from anon;
grant select on table public.honey_batches to anon;
grant select, insert on table public.honey_batches to authenticated;
